# Generated by Django 3.0.3 on 2020-10-12 07:17

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('raw_password', models.CharField(blank=True, max_length=30, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('referral', models.CharField(default=account.models.generateUUID, max_length=40, unique=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatar_image')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ic_number', models.IntegerField(blank=True, null=True)),
                ('user_pin', models.IntegerField(blank=True, null=True)),
                ('user_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_country', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, choices=[('-', '-'), ('MAYBANK', 'MAYBANK'), ('PUBLIC BANK', 'PUBLIC BANK'), ('RHB', 'RHB'), ('HSBC', 'HSBC'), ('CIMB', 'CIMB'), ('HONG LEONG', 'HONG LEONG'), ('AMBANK', 'AMBANK'), ('ALLIANCE BANK', 'ALLIANCE BANK')], max_length=50, null=True)),
                ('bank_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user_usdt_wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(choices=[('MEMBER', 'MEMBER'), ('ADMIN', 'ADMIN')], default='NORMAL', max_length=20)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
