# Generated by Django 3.0.3 on 2021-10-21 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211021_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckynumber',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='main.LuckyNumberOrders'),
        ),
    ]
